// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_providers.sql

package dao

import (
	"context"
)

const getActiveProviderToken = `-- name: GetActiveProviderToken :one
SELECT encrypted_token FROM access_providers
WHERE company_id = $1 AND provider_name = $2 AND status = 'active'
LIMIT 1
`

type GetActiveProviderTokenParams struct {
	CompanyID    *string `json:"company_id"`
	ProviderName string  `json:"provider_name"`
}

func (q *Queries) GetActiveProviderToken(ctx context.Context, arg GetActiveProviderTokenParams) (*string, error) {
	row := q.db.QueryRow(ctx, getActiveProviderToken, arg.CompanyID, arg.ProviderName)
	var encrypted_token *string
	err := row.Scan(&encrypted_token)
	return encrypted_token, err
}
