// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ae_messages.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAEMessage = `-- name: InsertAEMessage :one
INSERT INTO ae_messages (id, company_id, from_id, to_id, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertAEMessageParams struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	FromID    string `json:"from_id"`
	ToID      string `json:"to_id"`
	Message   string `json:"message"`
}

type InsertAEMessageRow struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAEMessage(ctx context.Context, arg InsertAEMessageParams) (InsertAEMessageRow, error) {
	row := q.db.QueryRow(ctx, insertAEMessage,
		arg.ID,
		arg.CompanyID,
		arg.FromID,
		arg.ToID,
		arg.Message,
	)
	var i InsertAEMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listUnreadMessages = `-- name: ListUnreadMessages :many
SELECT id, from_id, message, created_at
FROM ae_messages
WHERE to_id = $1 AND read = false
ORDER BY created_at ASC
LIMIT 10
`

type ListUnreadMessagesRow struct {
	ID        string             `json:"id"`
	FromID    string             `json:"from_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnreadMessages(ctx context.Context, toID string) ([]ListUnreadMessagesRow, error) {
	rows, err := q.db.Query(ctx, listUnreadMessages, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadMessagesRow{}
	for rows.Next() {
		var i ListUnreadMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE ae_messages SET read = true WHERE to_id = $1 AND read = false
`

func (q *Queries) MarkMessagesAsRead(ctx context.Context, toID string) error {
	_, err := q.db.Exec(ctx, markMessagesAsRead, toID)
	return err
}
