// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompany = `-- name: GetCompany :one
SELECT id, name, mission, status, created_at, policy_doc, slack_team_id, slack_team_name FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mission,
		&i.Status,
		&i.CreatedAt,
		&i.PolicyDoc,
		&i.SlackTeamID,
		&i.SlackTeamName,
	)
	return i, err
}

const insertCompany = `-- name: InsertCompany :one
INSERT INTO companies (id, name, mission, status, created_at, policy_doc)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, mission, status, created_at, policy_doc, slack_team_id, slack_team_name
`

type InsertCompanyParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Mission   *string            `json:"mission"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	PolicyDoc *string            `json:"policy_doc"`
}

func (q *Queries) InsertCompany(ctx context.Context, arg InsertCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, insertCompany,
		arg.ID,
		arg.Name,
		arg.Mission,
		arg.Status,
		arg.CreatedAt,
		arg.PolicyDoc,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mission,
		&i.Status,
		&i.CreatedAt,
		&i.PolicyDoc,
		&i.SlackTeamID,
		&i.SlackTeamName,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, mission, status, created_at, policy_doc, slack_team_id, slack_team_name FROM companies ORDER BY created_at DESC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mission,
			&i.Status,
			&i.CreatedAt,
			&i.PolicyDoc,
			&i.SlackTeamID,
			&i.SlackTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyPolicy = `-- name: UpdateCompanyPolicy :exec
UPDATE companies SET policy_doc = $2 WHERE id = $1
`

type UpdateCompanyPolicyParams struct {
	ID        string  `json:"id"`
	PolicyDoc *string `json:"policy_doc"`
}

func (q *Queries) UpdateCompanyPolicy(ctx context.Context, arg UpdateCompanyPolicyParams) error {
	_, err := q.db.Exec(ctx, updateCompanyPolicy, arg.ID, arg.PolicyDoc)
	return err
}

const updateCompanyStatus = `-- name: UpdateCompanyStatus :exec
UPDATE companies SET status = $2 WHERE id = $1
`

type UpdateCompanyStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateCompanyStatus(ctx context.Context, arg UpdateCompanyStatusParams) error {
	_, err := q.db.Exec(ctx, updateCompanyStatus, arg.ID, arg.Status)
	return err
}
