// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_financials.sql

package dao

import (
	"context"
)

const getCompanyFinancials = `-- name: GetCompanyFinancials :one
SELECT id, company_id, bank_name, account_name, bsb, account_number, swift_code, payment_provider, payment_provider_config, invoice_prefix, invoice_counter, currency, created_at, updated_at FROM company_financials WHERE company_id = $1
`

func (q *Queries) GetCompanyFinancials(ctx context.Context, companyID string) (CompanyFinancial, error) {
	row := q.db.QueryRow(ctx, getCompanyFinancials, companyID)
	var i CompanyFinancial
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.AccountName,
		&i.Bsb,
		&i.AccountNumber,
		&i.SwiftCode,
		&i.PaymentProvider,
		&i.PaymentProviderConfig,
		&i.InvoicePrefix,
		&i.InvoiceCounter,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompanyFinancials = `-- name: UpsertCompanyFinancials :exec
INSERT INTO company_financials
  (id, company_id, bank_name, account_name, bsb, account_number,
   swift_code, payment_provider, invoice_prefix, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (company_id) DO UPDATE SET
  bank_name = $3, account_name = $4, bsb = $5, account_number = $6,
  swift_code = $7, payment_provider = $8, invoice_prefix = $9, currency = $10,
  updated_at = NOW()
`

type UpsertCompanyFinancialsParams struct {
	ID              string  `json:"id"`
	CompanyID       string  `json:"company_id"`
	BankName        *string `json:"bank_name"`
	AccountName     *string `json:"account_name"`
	Bsb             *string `json:"bsb"`
	AccountNumber   *string `json:"account_number"`
	SwiftCode       *string `json:"swift_code"`
	PaymentProvider *string `json:"payment_provider"`
	InvoicePrefix   *string `json:"invoice_prefix"`
	Currency        *string `json:"currency"`
}

func (q *Queries) UpsertCompanyFinancials(ctx context.Context, arg UpsertCompanyFinancialsParams) error {
	_, err := q.db.Exec(ctx, upsertCompanyFinancials,
		arg.ID,
		arg.CompanyID,
		arg.BankName,
		arg.AccountName,
		arg.Bsb,
		arg.AccountNumber,
		arg.SwiftCode,
		arg.PaymentProvider,
		arg.InvoicePrefix,
		arg.Currency,
	)
	return err
}
