// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveKBEntries = `-- name: CountActiveKBEntries :one
SELECT COUNT(*) FROM knowledgebase WHERE status = 'active'
`

func (q *Queries) CountActiveKBEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveKBEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM tasks
`

func (q *Queries) CountTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAEsWithLastActive = `-- name: ListAEsWithLastActive :many
SELECT e.id, e.company_id, COALESCE(e.name,'') as name, e.role, COALESCE(e.specialties,'') as specialties,
       e.type, e.status, COALESCE(e.slack_user_id,'') as slack_user_id, e.created_at,
       MAX(tl.created_at) as last_active
FROM employees e
LEFT JOIN tool_logs tl ON tl.employee_id = e.id
WHERE e.type = 'ae'
GROUP BY e.id, e.company_id, e.name, e.role, e.specialties, e.type, e.status, e.slack_user_id, e.created_at
ORDER BY e.created_at DESC
`

type ListAEsWithLastActiveRow struct {
	ID          string             `json:"id"`
	CompanyID   string             `json:"company_id"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	Specialties string             `json:"specialties"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	SlackUserID string             `json:"slack_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastActive  interface{}        `json:"last_active"`
}

func (q *Queries) ListAEsWithLastActive(ctx context.Context) ([]ListAEsWithLastActiveRow, error) {
	rows, err := q.db.Query(ctx, listAEsWithLastActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAEsWithLastActiveRow{}
	for rows.Next() {
		var i ListAEsWithLastActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Role,
			&i.Specialties,
			&i.Type,
			&i.Status,
			&i.SlackUserID,
			&i.CreatedAt,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTeamWorkItems = `-- name: ListActiveTeamWorkItems :many
SELECT COALESCE(e.name, e.role) as owner_name, e.role as owner_role, wi.title, wi.status, wi.priority, wi.updated_at
FROM work_items wi
JOIN employees e ON e.id = wi.owner_id
WHERE wi.status IN ('in_progress', 'todo', 'blocked')
ORDER BY CASE wi.status WHEN 'in_progress' THEN 0 WHEN 'blocked' THEN 1 ELSE 2 END, wi.updated_at DESC
LIMIT 30
`

type ListActiveTeamWorkItemsRow struct {
	OwnerName string             `json:"owner_name"`
	OwnerRole string             `json:"owner_role"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveTeamWorkItems(ctx context.Context) ([]ListActiveTeamWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTeamWorkItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTeamWorkItemsRow{}
	for rows.Next() {
		var i ListActiveTeamWorkItemsRow
		if err := rows.Scan(
			&i.OwnerName,
			&i.OwnerRole,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEmployeesWithLastActive = `-- name: ListAllEmployeesWithLastActive :many
SELECT e.id, e.company_id, COALESCE(e.name,'') as name, e.role, COALESCE(e.specialties,'') as specialties,
       e.type, e.status, COALESCE(e.slack_user_id,'') as slack_user_id, e.created_at,
       MAX(tl.created_at) as last_active
FROM employees e
LEFT JOIN tool_logs tl ON tl.employee_id = e.id
GROUP BY e.id, e.company_id, e.name, e.role, e.specialties, e.type, e.status, e.slack_user_id, e.created_at
ORDER BY e.type, e.created_at DESC
`

type ListAllEmployeesWithLastActiveRow struct {
	ID          string             `json:"id"`
	CompanyID   string             `json:"company_id"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	Specialties string             `json:"specialties"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	SlackUserID string             `json:"slack_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastActive  interface{}        `json:"last_active"`
}

func (q *Queries) ListAllEmployeesWithLastActive(ctx context.Context) ([]ListAllEmployeesWithLastActiveRow, error) {
	rows, err := q.db.Query(ctx, listAllEmployeesWithLastActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEmployeesWithLastActiveRow{}
	for rows.Next() {
		var i ListAllEmployeesWithLastActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Role,
			&i.Specialties,
			&i.Type,
			&i.Status,
			&i.SlackUserID,
			&i.CreatedAt,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentToolLogsWithEmployee = `-- name: ListRecentToolLogsWithEmployee :many
SELECT tl.id, tl.employee_id, COALESCE(e.name, e.role, tl.employee_id) as employee_name,
       tl.tool, tl.action, tl.success, COALESCE(tl.trace_id,'') as trace_id,
       COALESCE(tl.task_id,'') as task_id, tl.created_at
FROM tool_logs tl
LEFT JOIN employees e ON e.id = tl.employee_id
ORDER BY tl.created_at DESC
LIMIT $1
`

type ListRecentToolLogsWithEmployeeRow struct {
	ID           string             `json:"id"`
	EmployeeID   string             `json:"employee_id"`
	EmployeeName string             `json:"employee_name"`
	Tool         string             `json:"tool"`
	Action       string             `json:"action"`
	Success      bool               `json:"success"`
	TraceID      string             `json:"trace_id"`
	TaskID       string             `json:"task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentToolLogsWithEmployee(ctx context.Context, limit int32) ([]ListRecentToolLogsWithEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listRecentToolLogsWithEmployee, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentToolLogsWithEmployeeRow{}
	for rows.Next() {
		var i ListRecentToolLogsWithEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.Tool,
			&i.Action,
			&i.Success,
			&i.TraceID,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolLogsWithEmployeeAll = `-- name: ListToolLogsWithEmployeeAll :many
SELECT tl.id, tl.employee_id, COALESCE(e.name, e.role, tl.employee_id) as employee_name,
       tl.tool, tl.action, tl.success, COALESCE(tl.trace_id,'') as trace_id,
       COALESCE(tl.task_id,'') as task_id, tl.created_at
FROM tool_logs tl
LEFT JOIN employees e ON e.id = tl.employee_id
ORDER BY tl.created_at DESC
LIMIT 200
`

type ListToolLogsWithEmployeeAllRow struct {
	ID           string             `json:"id"`
	EmployeeID   string             `json:"employee_id"`
	EmployeeName string             `json:"employee_name"`
	Tool         string             `json:"tool"`
	Action       string             `json:"action"`
	Success      bool               `json:"success"`
	TraceID      string             `json:"trace_id"`
	TaskID       string             `json:"task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListToolLogsWithEmployeeAll(ctx context.Context) ([]ListToolLogsWithEmployeeAllRow, error) {
	rows, err := q.db.Query(ctx, listToolLogsWithEmployeeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolLogsWithEmployeeAllRow{}
	for rows.Next() {
		var i ListToolLogsWithEmployeeAllRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.Tool,
			&i.Action,
			&i.Success,
			&i.TraceID,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolLogsWithEmployeeByEmployee = `-- name: ListToolLogsWithEmployeeByEmployee :many
SELECT tl.id, tl.employee_id, COALESCE(e.name, e.role, tl.employee_id) as employee_name,
       tl.tool, tl.action, tl.success, COALESCE(tl.trace_id,'') as trace_id,
       COALESCE(tl.task_id,'') as task_id, tl.created_at
FROM tool_logs tl
LEFT JOIN employees e ON e.id = tl.employee_id
WHERE tl.employee_id = $1
ORDER BY tl.created_at DESC
LIMIT 200
`

type ListToolLogsWithEmployeeByEmployeeRow struct {
	ID           string             `json:"id"`
	EmployeeID   string             `json:"employee_id"`
	EmployeeName string             `json:"employee_name"`
	Tool         string             `json:"tool"`
	Action       string             `json:"action"`
	Success      bool               `json:"success"`
	TraceID      string             `json:"trace_id"`
	TaskID       string             `json:"task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListToolLogsWithEmployeeByEmployee(ctx context.Context, employeeID string) ([]ListToolLogsWithEmployeeByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listToolLogsWithEmployeeByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolLogsWithEmployeeByEmployeeRow{}
	for rows.Next() {
		var i ListToolLogsWithEmployeeByEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.Tool,
			&i.Action,
			&i.Success,
			&i.TraceID,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolLogsWithEmployeeByEmployeeAndTool = `-- name: ListToolLogsWithEmployeeByEmployeeAndTool :many
SELECT tl.id, tl.employee_id, COALESCE(e.name, e.role, tl.employee_id) as employee_name,
       tl.tool, tl.action, tl.success, COALESCE(tl.trace_id,'') as trace_id,
       COALESCE(tl.task_id,'') as task_id, tl.created_at
FROM tool_logs tl
LEFT JOIN employees e ON e.id = tl.employee_id
WHERE tl.employee_id = $1 AND tl.tool ILIKE $2
ORDER BY tl.created_at DESC
LIMIT 200
`

type ListToolLogsWithEmployeeByEmployeeAndToolParams struct {
	EmployeeID string `json:"employee_id"`
	Tool       string `json:"tool"`
}

type ListToolLogsWithEmployeeByEmployeeAndToolRow struct {
	ID           string             `json:"id"`
	EmployeeID   string             `json:"employee_id"`
	EmployeeName string             `json:"employee_name"`
	Tool         string             `json:"tool"`
	Action       string             `json:"action"`
	Success      bool               `json:"success"`
	TraceID      string             `json:"trace_id"`
	TaskID       string             `json:"task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListToolLogsWithEmployeeByEmployeeAndTool(ctx context.Context, arg ListToolLogsWithEmployeeByEmployeeAndToolParams) ([]ListToolLogsWithEmployeeByEmployeeAndToolRow, error) {
	rows, err := q.db.Query(ctx, listToolLogsWithEmployeeByEmployeeAndTool, arg.EmployeeID, arg.Tool)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolLogsWithEmployeeByEmployeeAndToolRow{}
	for rows.Next() {
		var i ListToolLogsWithEmployeeByEmployeeAndToolRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.Tool,
			&i.Action,
			&i.Success,
			&i.TraceID,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolLogsWithEmployeeByTool = `-- name: ListToolLogsWithEmployeeByTool :many
SELECT tl.id, tl.employee_id, COALESCE(e.name, e.role, tl.employee_id) as employee_name,
       tl.tool, tl.action, tl.success, COALESCE(tl.trace_id,'') as trace_id,
       COALESCE(tl.task_id,'') as task_id, tl.created_at
FROM tool_logs tl
LEFT JOIN employees e ON e.id = tl.employee_id
WHERE tl.tool ILIKE $1
ORDER BY tl.created_at DESC
LIMIT 200
`

type ListToolLogsWithEmployeeByToolRow struct {
	ID           string             `json:"id"`
	EmployeeID   string             `json:"employee_id"`
	EmployeeName string             `json:"employee_name"`
	Tool         string             `json:"tool"`
	Action       string             `json:"action"`
	Success      bool               `json:"success"`
	TraceID      string             `json:"trace_id"`
	TaskID       string             `json:"task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListToolLogsWithEmployeeByTool(ctx context.Context, tool string) ([]ListToolLogsWithEmployeeByToolRow, error) {
	rows, err := q.db.Query(ctx, listToolLogsWithEmployeeByTool, tool)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolLogsWithEmployeeByToolRow{}
	for rows.Next() {
		var i ListToolLogsWithEmployeeByToolRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.Tool,
			&i.Action,
			&i.Success,
			&i.TraceID,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsByOwnerNotCancelled = `-- name: ListWorkItemsByOwnerNotCancelled :many
SELECT id, title, status, priority, updated_at
FROM work_items
WHERE owner_id = $1 AND status NOT IN ('cancelled')
ORDER BY CASE status WHEN 'in_progress' THEN 0 WHEN 'blocked' THEN 1 WHEN 'todo' THEN 2 ELSE 3 END,
         CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
         updated_at DESC
LIMIT 20
`

type ListWorkItemsByOwnerNotCancelledRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkItemsByOwnerNotCancelled(ctx context.Context, ownerID string) ([]ListWorkItemsByOwnerNotCancelledRow, error) {
	rows, err := q.db.Query(ctx, listWorkItemsByOwnerNotCancelled, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkItemsByOwnerNotCancelledRow{}
	for rows.Next() {
		var i ListWorkItemsByOwnerNotCancelledRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
