// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledgebase.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveKBEntry = `-- name: ApproveKBEntry :exec
UPDATE knowledgebase SET status = 'active', approved_by = $2 WHERE id = $1
`

type ApproveKBEntryParams struct {
	ID         string  `json:"id"`
	ApprovedBy *string `json:"approved_by"`
}

func (q *Queries) ApproveKBEntry(ctx context.Context, arg ApproveKBEntryParams) error {
	_, err := q.db.Exec(ctx, approveKBEntry, arg.ID, arg.ApprovedBy)
	return err
}

const getAllKBEntries = `-- name: GetAllKBEntries :many
SELECT id, company_id, title, content, tags, status, approved_by, created_at FROM knowledgebase WHERE company_id = $1 AND status = 'active' ORDER BY created_at DESC
`

func (q *Queries) GetAllKBEntries(ctx context.Context, companyID string) ([]Knowledgebase, error) {
	rows, err := q.db.Query(ctx, getAllKBEntries, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Knowledgebase{}
	for rows.Next() {
		var i Knowledgebase
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.Status,
			&i.ApprovedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertKBEntry = `-- name: InsertKBEntry :one
INSERT INTO knowledgebase (id, company_id, title, content, tags, status, approved_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, title, content, tags, status, approved_by, created_at
`

type InsertKBEntryParams struct {
	ID         string             `json:"id"`
	CompanyID  string             `json:"company_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Tags       []string           `json:"tags"`
	Status     string             `json:"status"`
	ApprovedBy *string            `json:"approved_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertKBEntry(ctx context.Context, arg InsertKBEntryParams) (Knowledgebase, error) {
	row := q.db.QueryRow(ctx, insertKBEntry,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.Status,
		arg.ApprovedBy,
		arg.CreatedAt,
	)
	var i Knowledgebase
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Status,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const searchKBEntries = `-- name: SearchKBEntries :many
SELECT id, company_id, title, content, tags, status, approved_by, created_at FROM knowledgebase WHERE company_id = $1 AND (title ILIKE $2 OR content ILIKE $2)
`

type SearchKBEntriesParams struct {
	CompanyID string `json:"company_id"`
	Title     string `json:"title"`
}

func (q *Queries) SearchKBEntries(ctx context.Context, arg SearchKBEntriesParams) ([]Knowledgebase, error) {
	rows, err := q.db.Query(ctx, searchKBEntries, arg.CompanyID, arg.Title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Knowledgebase{}
	for rows.Next() {
		var i Knowledgebase
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.Status,
			&i.ApprovedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
