// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack_events.sql

package dao

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnprocessedSlackEvents = `-- name: GetUnprocessedSlackEvents :many
SELECT id, company_id, event_type, channel, user_id, thread_ts, message_ts, payload, processed_at, created_at FROM slack_events WHERE processed_at IS NULL AND company_id = $1 ORDER BY created_at LIMIT $2
`

type GetUnprocessedSlackEventsParams struct {
	CompanyID string `json:"company_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetUnprocessedSlackEvents(ctx context.Context, arg GetUnprocessedSlackEventsParams) ([]SlackEvent, error) {
	rows, err := q.db.Query(ctx, getUnprocessedSlackEvents, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackEvent{}
	for rows.Next() {
		var i SlackEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EventType,
			&i.Channel,
			&i.UserID,
			&i.ThreadTs,
			&i.MessageTs,
			&i.Payload,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSlackEvent = `-- name: InsertSlackEvent :one
INSERT INTO slack_events (id, company_id, event_type, channel, user_id, thread_ts, message_ts, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, event_type, channel, user_id, thread_ts, message_ts, payload, processed_at, created_at
`

type InsertSlackEventParams struct {
	ID        string             `json:"id"`
	CompanyID string             `json:"company_id"`
	EventType string             `json:"event_type"`
	Channel   *string            `json:"channel"`
	UserID    *string            `json:"user_id"`
	ThreadTs  *string            `json:"thread_ts"`
	MessageTs *string            `json:"message_ts"`
	Payload   json.RawMessage    `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSlackEvent(ctx context.Context, arg InsertSlackEventParams) (SlackEvent, error) {
	row := q.db.QueryRow(ctx, insertSlackEvent,
		arg.ID,
		arg.CompanyID,
		arg.EventType,
		arg.Channel,
		arg.UserID,
		arg.ThreadTs,
		arg.MessageTs,
		arg.Payload,
		arg.CreatedAt,
	)
	var i SlackEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EventType,
		&i.Channel,
		&i.UserID,
		&i.ThreadTs,
		&i.MessageTs,
		&i.Payload,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markSlackEventProcessed = `-- name: MarkSlackEventProcessed :exec
UPDATE slack_events SET processed_at = NOW() WHERE id = $1
`

func (q *Queries) MarkSlackEventProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markSlackEventProcessed, id)
	return err
}
