// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool_logs.sql

package dao

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentToolLogs = `-- name: GetRecentToolLogs :many
SELECT id, employee_id, tool, action, input, output, success, trace_id, task_id, created_at, company_id FROM tool_logs WHERE company_id IS NOT NULL ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) GetRecentToolLogs(ctx context.Context, limit int32) ([]ToolLog, error) {
	rows, err := q.db.Query(ctx, getRecentToolLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolLog{}
	for rows.Next() {
		var i ToolLog
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Tool,
			&i.Action,
			&i.Input,
			&i.Output,
			&i.Success,
			&i.TraceID,
			&i.TaskID,
			&i.CreatedAt,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolLogsByEmployee = `-- name: GetToolLogsByEmployee :many
SELECT id, employee_id, tool, action, input, output, success, trace_id, task_id, created_at, company_id FROM tool_logs WHERE employee_id = $1 ORDER BY created_at DESC LIMIT $2
`

type GetToolLogsByEmployeeParams struct {
	EmployeeID string `json:"employee_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetToolLogsByEmployee(ctx context.Context, arg GetToolLogsByEmployeeParams) ([]ToolLog, error) {
	rows, err := q.db.Query(ctx, getToolLogsByEmployee, arg.EmployeeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolLog{}
	for rows.Next() {
		var i ToolLog
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Tool,
			&i.Action,
			&i.Input,
			&i.Output,
			&i.Success,
			&i.TraceID,
			&i.TaskID,
			&i.CreatedAt,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertToolLog = `-- name: InsertToolLog :one
INSERT INTO tool_logs (id, employee_id, company_id, tool, action, input, output, success, trace_id, task_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, employee_id, tool, action, input, output, success, trace_id, task_id, created_at, company_id
`

type InsertToolLogParams struct {
	ID         string             `json:"id"`
	EmployeeID string             `json:"employee_id"`
	CompanyID  *string            `json:"company_id"`
	Tool       string             `json:"tool"`
	Action     string             `json:"action"`
	Input      json.RawMessage    `json:"input"`
	Output     json.RawMessage    `json:"output"`
	Success    bool               `json:"success"`
	TraceID    *string            `json:"trace_id"`
	TaskID     *string            `json:"task_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertToolLog(ctx context.Context, arg InsertToolLogParams) (ToolLog, error) {
	row := q.db.QueryRow(ctx, insertToolLog,
		arg.ID,
		arg.EmployeeID,
		arg.CompanyID,
		arg.Tool,
		arg.Action,
		arg.Input,
		arg.Output,
		arg.Success,
		arg.TraceID,
		arg.TaskID,
		arg.CreatedAt,
	)
	var i ToolLog
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Tool,
		&i.Action,
		&i.Input,
		&i.Output,
		&i.Success,
		&i.TraceID,
		&i.TaskID,
		&i.CreatedAt,
		&i.CompanyID,
	)
	return i, err
}
