// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work_items.sql

package dao

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkItemHistory = `-- name: AddWorkItemHistory :exec
INSERT INTO work_item_history (id, work_item_id, change_type, content, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type AddWorkItemHistoryParams struct {
	ID         string          `json:"id"`
	WorkItemID string          `json:"work_item_id"`
	ChangeType string          `json:"change_type"`
	Content    *string         `json:"content"`
	Metadata   json.RawMessage `json:"metadata"`
}

func (q *Queries) AddWorkItemHistory(ctx context.Context, arg AddWorkItemHistoryParams) error {
	_, err := q.db.Exec(ctx, addWorkItemHistory,
		arg.ID,
		arg.WorkItemID,
		arg.ChangeType,
		arg.Content,
		arg.Metadata,
	)
	return err
}

const createWorkItem = `-- name: CreateWorkItem :one
INSERT INTO work_items (id, parent_id, company_id, owner_id, title, description, status, priority, source_task_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, status, priority, created_at
`

type CreateWorkItemParams struct {
	ID           string  `json:"id"`
	ParentID     *string `json:"parent_id"`
	CompanyID    string  `json:"company_id"`
	OwnerID      string  `json:"owner_id"`
	Title        string  `json:"title"`
	Description  *string `json:"description"`
	Status       string  `json:"status"`
	Priority     string  `json:"priority"`
	SourceTaskID *string `json:"source_task_id"`
}

type CreateWorkItemRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWorkItem(ctx context.Context, arg CreateWorkItemParams) (CreateWorkItemRow, error) {
	row := q.db.QueryRow(ctx, createWorkItem,
		arg.ID,
		arg.ParentID,
		arg.CompanyID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.SourceTaskID,
	)
	var i CreateWorkItemRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkItem = `-- name: GetWorkItem :one
SELECT id, COALESCE(parent_id,'') as parent_id, company_id, owner_id, title, COALESCE(description,'') as description, status, priority, COALESCE(source_task_id,'') as source_task_id, created_at, updated_at
FROM work_items WHERE id = $1
`

type GetWorkItemRow struct {
	ID           string             `json:"id"`
	ParentID     string             `json:"parent_id"`
	CompanyID    string             `json:"company_id"`
	OwnerID      string             `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       string             `json:"status"`
	Priority     string             `json:"priority"`
	SourceTaskID string             `json:"source_task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkItem(ctx context.Context, id string) (GetWorkItemRow, error) {
	row := q.db.QueryRow(ctx, getWorkItem, id)
	var i GetWorkItemRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CompanyID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.SourceTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkItemsByCompany = `-- name: ListWorkItemsByCompany :many
SELECT wi.id, COALESCE(e.name, e.role) as owner_name, e.role as owner_role, wi.title, wi.status, wi.priority, wi.updated_at
FROM work_items wi
JOIN employees e ON e.id = wi.owner_id
WHERE wi.company_id = $1 AND wi.status IN ('in_progress', 'todo', 'blocked')
ORDER BY CASE wi.status WHEN 'in_progress' THEN 0 WHEN 'blocked' THEN 1 ELSE 2 END, wi.updated_at DESC
LIMIT 30
`

type ListWorkItemsByCompanyRow struct {
	ID        string             `json:"id"`
	OwnerName string             `json:"owner_name"`
	OwnerRole string             `json:"owner_role"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkItemsByCompany(ctx context.Context, companyID string) ([]ListWorkItemsByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listWorkItemsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkItemsByCompanyRow{}
	for rows.Next() {
		var i ListWorkItemsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerName,
			&i.OwnerRole,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItemsByOwner = `-- name: ListWorkItemsByOwner :many
SELECT id, COALESCE(parent_id,'') as parent_id, title, COALESCE(description,'') as description, status, priority, updated_at
FROM work_items
WHERE owner_id = $1 AND status NOT IN ('done', 'cancelled')
ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, created_at ASC
LIMIT 20
`

type ListWorkItemsByOwnerRow struct {
	ID          string             `json:"id"`
	ParentID    string             `json:"parent_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkItemsByOwner(ctx context.Context, ownerID string) ([]ListWorkItemsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listWorkItemsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkItemsByOwnerRow{}
	for rows.Next() {
		var i ListWorkItemsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkItemStatus = `-- name: UpdateWorkItemStatus :exec
UPDATE work_items SET status = $2, updated_at = now() WHERE id = $1 AND owner_id = $3
`

type UpdateWorkItemStatusParams struct {
	ID      string `json:"id"`
	Status  string `json:"status"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) UpdateWorkItemStatus(ctx context.Context, arg UpdateWorkItemStatusParams) error {
	_, err := q.db.Exec(ctx, updateWorkItemStatus, arg.ID, arg.Status, arg.OwnerID)
	return err
}
